### ISSUE TITLE
Build error: framework not found

### ISSUE THREAD

**Issue by nesevis** [spouliot/xcframework#1] opened 2021-03-01 21:31 UTC
While investigating the state of `xcframework` support in Xamarin I tested this project, which I believe was created as part of the work to add initial support.

There may have been some sort of regression here, as this project build fails with this error:

```
error MT5209 : Native linking error : framework not found Universal
```

Update: I can get my `xcframework` to work in the preview stream of VSfM, but only when added as a native reference. An _mtouch_ argument `--framework:"path-to-xcframework"` does not work.

This project throws the following error in the preview stream:

```
../../Universal.xcframework has an incorrect or unknown format and cannot be processed.
```

**Comment by spouliot** [comment] 2021-03-01 22:38
Thanks for the feedback but this repo is not meant to get issues and I'm not monitoring all my tests repos.

It's also hard to diagnose without knowing which version(s) of all the tools you're using. Please open an issue on the main repo and provide the requested information: https://github.com/xamarin/xamarin-macios/issues/new

> `--framework:"path-to-xcframework"` does not work.

It's by design. 
1. An xcframework is not a framework (it's actually a collection of frameworks);
2. XCFrameworks are resolved into frameworks by `msbuild`, which then calls `mtouch`. The latter does not know anything about XCFrameworks (and we do not want to duplicate the code/logic in multiple places).

If you want you can still use the **Additional mtouch arguments** you should do the same, i.e. provide the path to the correct framework directory (inside the xcframework directory).

**Closed by spouliot** 2021-03-01 22:38 UTC
